vich_uploader:
  db_driver: orm
  mappings:
    user_images:
      uri_prefix:         '%app.path.uploads_dir%'
      upload_destination: '%kernel.root_dir%/../public/%app.path.uploads_dir%'
      namer: vich_uploader.namer_uniqid

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true